Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OBPostupy.Data;
using OBPostupy.ViewModels;
using OBPostupy.Extensions.Messages;
using OBPostupy.Models.Courses;
using OBPostupy.Models.Races;
using OBPostupy.Models.Results;
using System.Text.Json;
using System.Text.Json.Serialization;
using EFCore.BulkExtensions;

namespace OBPostupy.Controllers
{
    public class CoursesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        public CoursesController(ApplicationDbContext context):base(context)
        {
            _context = context;
        }

        /// <summary>
        /// File upload action for course data
        /// </summary>
        /// <param name="id">ID of race</param>
        /// <param name="file">File data</param>
        /// <returns>Redirect to setting of race</returns>
        [HttpPost]
        public async Task<IActionResult> UploadCourses(int? id, IFormFile file)
        {
            if (id == null  || file == null)
            {
                return NotFound();
            }

            var race = await _context.Races.SingleOrDefaultAsync(r => r.ID == id);

            if (race == null)
            {
                return NotFound();
            }

            if (file.Length > 0)
            {
                var courseFilePath = Path.GetTempFileName();

                using (var stream = System.IO.File.Create(courseFilePath))
                {
                    await file.CopyToAsync(stream);
                }
                CourseReader courseReader = new CourseReader(courseFilePath);
                courseReader.Read();
                CourseData courseData = new CourseData {
                       Controls = courseReader.Controls,
                       Splits = courseReader.Splits,
                       Courses = courseReader.Courses,
                       Race = race
                };
                _context.CourseData.Add(courseData);
                _context.CourseControls.AddRange(courseReader.CourseControls);
                _context.CourseSplits.AddRange(courseReader.CourseSplits);
                await _context.SaveChangesAsync();
                return RedirectToAction("Setting", "Races", new { id = id }).Success("Tratě a kontroly nahrány.");

            }
            return RedirectToAction("Setting", "Races", new { id = id }).Danger("Tratě a kontroly NEbyly nahrány.");
        }

        /// <summary>
        /// Action for delete course data
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Page with comfirmation</returns>

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await GetSingleRaceAsync(r => r.ID == id);
            if (race == null)
            {
                return NotFound();
            }
            
            return View();
        }

        /// <summary>
        /// Delete confirmation 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await GetSingleRaceAsync(r => r.ID == id);
            if (race == null)
            {
                return NotFound();
            }

            try
            {
                var splits = _context.Splits.Where(c => c.CourseData == race.CourseData).ToList();
                _context.Splits.RemoveRange(splits);
                await _context.SaveChangesAsync();

                var controls = _context.Controls.Where(c => c.CourseData == race.CourseData).ToList();
                _context.Controls.RemoveRange(controls);
                await _context.SaveChangesAsync();

                var courses = _context.Courses.Where(c => c.CourseData == race.CourseData).ToList();
                _context.Courses.RemoveRange(courses);
                _context.CourseData.Remove(race.CourseData);
                await _context.SaveChangesAsync();
                return RedirectToAction("Setting", "Races", new { id = id }).Success("Tratě a kontroly byly smazány");

            }
            catch (Exception)
            {
                return RedirectToAction("Setting", "Races", new { id = id }).Danger("Tratě a kontroly NEbyly smazány, nastal nějaký problém.");
            }

        }

        /// <summary>
        /// Action for returning a serialized course in JSON
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Course in JSON</returns>
        [HttpGet]
        public async Task<IActionResult> GetCourse(int? id)
        {
            
            if(id == null)
            {
                return NotFound();
            }

            var course = await GetSingleCourseWithControlsAsync(c => c.ID == id);

            if (course == null)
            {
                return NotFound();
            }

            var options = new Newtonsoft.Json.JsonSerializerSettings
            {
                MaxDepth = 3,
                NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore,
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
            };
            return Json(course, options);
        }

    }
}

Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OBPostupy.Data;
using OBPostupy.Models.Races;
using OBPostupy.Models.Maps;
using Microsoft.AspNetCore.Hosting;
using OBPostupy.Extensions.Messages;
using System.Diagnostics;

namespace OBPostupy.Controllers
{
    public class MapsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;
        public MapsController(ApplicationDbContext context, IWebHostEnvironment env):base(context)
        {
            _context = context;
            _env = env;
        }


        /// <summary>
        /// File upload action for map data
        /// </summary>
        /// <param name="id"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UploadMap(int? id, IFormFile file)
        {            
            if(id == null)
            {
                return NotFound();
            }  
            
            var race = await _context.Races.SingleOrDefaultAsync(r => r.ID == id); 

            if (race == null)
            {
                return NotFound();
            }
            if (file.Length > 0)
            {
                var mapFilePath = Path.GetTempFileName();

                using (var stream = System.IO.File.Create(mapFilePath))
                {
                    await file.CopyToAsync(stream);
                }
                MapReader mapReader = new MapReader(_env.WebRootPath,mapFilePath, Path.GetExtension(file.FileName).ToLowerInvariant());
                Map map = mapReader.Read();
                if(map != null)
                {
                    map.Race = race;
                    _context.Maps.Add(map);
                    _context.SaveChanges();
                    return RedirectToAction("Setting", "Races", new { id = id }).Success("Mapa byla nahrána.");
                }

            }
            return RedirectToAction("Setting", "Races", new { id = id }).Danger("Mapa nebyla nahrána.");
        }

        /// <summary>
        /// Actions for showing the map image
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Show(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.Include(r => r.Map)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (race == null || race.Map == null)
            {
                return NotFound();
            }

            string pathToImage = Path.Combine(_env.WebRootPath, race.Map.PathToFile);
            var extension = Path.GetExtension(pathToImage);
            if (System.IO.File.Exists(pathToImage))
            {
                return Redirect("~/" + race.Map.PathToFile);
            }

            return NotFound();
        }

        /// <summary>
        /// Action for delete map
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.Include(r => r.Map)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (race == null || race.Map == null)
            {
                return NotFound();
            }

            return View(race.Map);
        }

        /// <summary>
        /// Delete comfirmation
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var race = await _context.Races.Include(r => r.Map).FirstOrDefaultAsync(m => m.ID == id);

            if (race == null || race.Map == null)
            {
                return NotFound();
            }

            string pathToImage = Path.Combine(_env.WebRootPath, race.Map.PathToFile);
            if (System.IO.File.Exists(pathToImage))
            {
                System.IO.File.Delete(pathToImage);
            }

            try
            {
                _context.Maps.Remove(race.Map);
                await _context.SaveChangesAsync();
                return RedirectToAction("Setting", "Races", new { id = race.ID}).Success("Mapa byla smazána.");
            }
            catch (Exception)
            {
                return RedirectToAction("Setting", "Races", new { id = race.ID }).Danger("Mapa NEbyla smazána, nastal nějaký problém.");
            }
        }
    }
}

Controllers/PathsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OBPostupy.Data;
using Microsoft.EntityFrameworkCore;
using EFCore.BulkExtensions;
using OBPostupy.Extensions.Messages;
using System.IO;
using OBPostupy.Models;
using OBPostupy.Models.GPS;
using System.Diagnostics;
using OBPostupy.Models.Results;
using Microsoft.AspNetCore.Identity;
namespace OBPostupy.Controllers
{
    public class PathsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        public PathsController(ApplicationDbContext context):base(context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Upload(int? raceID, int? competitorID, IFormFile file)
        {
            if (raceID == null || competitorID == null)
            {
                return NotFound();
            }
            var race = await _context.Races.SingleOrDefaultAsync(r => r.ID == raceID);
            var competitor = await _context.Person.SingleOrDefaultAsync(r => r.ID == competitorID);

            if (race == null || competitor == null)
            {
                return NotFound();
            }

            var personResult = await _context.PersonResults.Where(r => r.Person == competitor && r.Race == race).Include(pr => pr.Result).SingleOrDefaultAsync();
            if (personResult == null)
            {
                return NotFound();
            }

            if (file.Length > 0)
            {
                var gpxFilePath = System.IO.Path.GetTempFileName();

                using (var stream = System.IO.File.Create(gpxFilePath))
                {
                    await file.CopyToAsync(stream);
                }

                GpxReader gpxReader = new GpxReader(gpxFilePath);
                Models.GPS.Path path = gpxReader.Read();

                if (path != null)
                {                    
                    await GPSManipulationAsync(path, personResult);
                    return Ok(new { id = path.ID }); 
                }

            }
            return BadRequest();
        }
        
        private async Task GPSManipulationAsync(Models.GPS.Path path, PersonResult personResult)
        {
            var interpolated = pathAnalysis.InterpolationByTime(path.Locations, 1);
            var splits = await _context.SplitTimes.Where(st => st.Result == personResult.Result)
                                .Include(st => st.Split)
                                .ThenInclude(s => s.SecondControl)
                                .ToListAsync();

            double ofsset = pathAnalysis.GetOffsetFromSplits(splits, interpolated);
            var completeLocations = pathAnalysis.SetOffset(interpolated, ofsset);
           
            path.Locations = null;
            path.PersonResult = personResult;
            _context.Add(path);
            _context.SaveChanges();

            foreach (var cl in completeLocations)
            {
                cl.PathID = path.ID;
            }
            _context.BulkInsert(completeLocations);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var path = await _context.Paths.Include(p => p.PersonResult)
                                           .SingleOrDefaultAsync(r => r.ID == id);

            if (path == null)
            {
                return NotFound();
            }

            _context.Paths.Remove(path);
            _context.SaveChanges();

            return RedirectToAction("Details", "Races", new { id = path.PersonResult.RaceID });
        }

        [HttpGet]
        public async Task<IActionResult> GetPath(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var path = await GetSinglePathAsync(p => p.ID == id);

            if (path == null)
            {
                return NotFound();
            }

            var personResult = await GetSinglePersonResultAsync(pr => pr.PathID == path.ID);
            if (personResult == null)
            {
                return NotFound();
            }

            var splitTimeOfAllPath = new SplitTime { Time = path.PersonResult.Result.FinishTime, TimeSpan = (path.PersonResult.Result.FinishTime  - path.PersonResult.Result.StartTime).Seconds };
            var locationsTruncatedByResults = GetSplitPath(path, splitTimeOfAllPath);
            if (locationsTruncatedByResults != null)
            {
                path.Locations = locationsTruncatedByResults;
            }

            var options = new Newtonsoft.Json.JsonSerializerSettings
            {
                MaxDepth = 1,
                NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore,
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore,
                DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore
            };
            return Json(path, options);
        }

        [HttpGet]
        public async Task<IActionResult> GetCompletePath(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var path = await GetSinglePathAsync(r => r.ID == id);

            if (path == null)
            {
                return NotFound();
            }

            var interpolationByDistance = pathAnalysis.InterpolationByTime(path.Locations, 1);
            path.Locations = interpolationByDistance;

            var options = new Newtonsoft.Json.JsonSerializerSettings
            {
                MaxDepth = 1,
                NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore,
                ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore,
                DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore
            };
            return Json(path, options);
        }
        
       

    }
}

Views/Shared/Modals/_CourseToCategoryModal.cshtml
<div class="modal fade" id="courseCategoryModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="courseCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orisModalLabel">Přiřazení tratí</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="courseCategoryModalBody">

            </div>
        </div>
    </div>
</div>

Views/Shared/Modals/_DefaultModal.cshtml
<div class="modal fade" id="defaultModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" ></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

Views/Shared/Modals/_OrisModal.cshtml
@model OBPostupy.ViewModels.RaceSettingViewModel;

<div class="modal fade" id="orisModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="orisModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orisModalLabel">Stažení výsledků</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <label for="OrisEventDate">Datum závodů</label>
                    </div>
                    <div class="col-auto my-1">
                        <input type="date" class="form-control" id="OrisEventDate" placeholder="Datum závodu">
                    </div>
                    <div class="col-auto my-1">
                        <button type="button" class="btn btn-primary" id="ShowOrisEventList">Zobrazit</button>
                    </div>
                </div>
            </div>
            <form asp-controller="Results" asp-action="GetResults">
                <input type="hidden" name="ID" value="@Model.Race.ID" />
                <select id="OrisEventListSelect" asp-for="OrisEventID" class="custom-select my-2">
                </select>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                    <input type="submit" class="btn btn-primary" class="uploadLink" value="Uložit" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/Modals/_UploadCourseDataModal.cshtml
@model OBPostupy.ViewModels.RaceSettingViewModel;

<div class="modal fade" id="uploadCourseModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="uploadCourseModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orisModalLabel">Nahrání tratí a kontrol</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Courses" asp-action="UploadCourses" enctype="multipart/form-data">
                <div class="modal-body">
                    Nahrávejte kontroly a tratě ve formátu IOF XML v.3
                    <input type="file" class="form-control" name="file" />
                </div>
                <input type="hidden" name="id" value="@Model.Race.ID" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                    <input type="submit" class="btn btn-primary" class="uploadLink" value="Uložit" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/Modals/_UploadMapModal.cshtml
@model OBPostupy.ViewModels.RaceSettingViewModel;

<div class="modal fade" id="uploadMapModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="uploadMapModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orisModalLabel">Nahrání mapy</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Maps" asp-action="UploadMap" enctype="multipart/form-data">
                <div class="modal-body">
                    Nahrávejte mapu ve formátu KMZ
                    <input type="file" class="form-control" name="file" accept=".kmz" />
                </div>
                <input type="hidden" name="id" value="@Model.Race.ID" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                    <input type="submit" class="btn btn-primary" class="uploadLink" value="Uložit" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Shared/Modals/_UploadPathModal.cshtml
@model OBPostupy.ViewModels.RaceDetailViewModel

<div class="modal fade" id="uploadPathModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="uploadPathModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orisModalLabel">Nahrání GPS souboru</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div id="dropzone">
                    <form asp-controller="Paths" asp-action="Upload" enctype="multipart/form-data" class="dropzone dz-clickable" id="uploader">

                        <input type="hidden" name="raceID" value="@Model.Race.ID" />
                        <input class="upload-path-competitor-id" type="hidden" name="competitorID" />
                        <div class="dz-message d-flex flex-column justify-content-center align-items-center">
                            <i class="fas fa-file-upload fa-3x p-2"></i>
                            Přetáhněte sem GPX soubor nebo klikněte
                        </div>
                    </form>
                </div>

                @if (Model.HasStravaAccount)
                {
                    <div id="stravaActivitiesSection">
                        <div class="text-center"> nebo vyberte ze Stravy</div>
                        <div class="form-row align-items-center">
                            <div class="col-auto my-1">
                                <label for="stravaDate">Datum</label>
                            </div>
                            <div class="col-auto my-1">
                                <input type="date" class="form-control" id="stravaDate" placeholder="Datum">
                            </div>
                            <div class="col-auto my-1">
                                <button type="button" class="btn btn-primary" id="showStravaActivityList">Zobrazit</button>
                            </div>
                        </div>
                        <form asp-controller="Paths" asp-action="StravaUpload" id="selectStravaActivityForm">
                            <input type="hidden" name="raceID" value="@Model.Race.ID" />
                            <input class="upload-path-competitor-id" type="hidden" name="competitorID" />
                            <select id="stravaListSelect" name="stravaID" class="custom-select my-2">
                            </select>
                            <input type="submit" class="btn btn-primary" class="uploadLink" value="Nahrát závod ze Stravy" />
                        </form>
                    </div>
                }

            </div>
            <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
            </div>
        </div>
    </div>
</div>